"""empty message

Revision ID: 6f8a6db81405
Revises: 72158a7504fc
Create Date: 2022-02-07 12:44:14.053173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8a6db81405'
down_revision = '72158a7504fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint('likes_user_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['users_id'], ['id'])
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_user_id_fkey', 'likes', 'users', ['user_id'], ['id'])
    op.drop_column('likes', 'users_id')
    # ### end Alembic commands ###
