"""empty message

Revision ID: 48b0f135892c
Revises: e271790115c1
Create Date: 2022-02-07 12:23:59.758144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b0f135892c'
down_revision = 'e271790115c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.add_column('follows', sa.Column('follower_id', sa.Integer(), nullable=True))
    op.add_column('follows', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.drop_constraint('follows_followers_fkey', 'follows', type_='foreignkey')
    op.drop_constraint('follows_following_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    op.drop_column('follows', 'id')
    op.drop_column('follows', 'followers')
    op.drop_column('follows', 'following')
    op.add_column('likes', sa.Column('likes_id', sa.Integer(), nullable=True))
    op.add_column('likes', sa.Column('posts_id', sa.Integer(), nullable=True))
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')
    op.drop_constraint('likes_user_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['likes_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'posts', ['posts_id'], ['id'])
    op.drop_column('likes', 'id')
    op.drop_column('likes', 'post_id')
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('likes', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('likes', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_user_id_fkey', 'likes', 'users', ['user_id'], ['id'])
    op.create_foreign_key('likes_post_id_fkey', 'likes', 'posts', ['post_id'], ['id'])
    op.drop_column('likes', 'posts_id')
    op.drop_column('likes', 'likes_id')
    op.add_column('follows', sa.Column('following', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('follows', sa.Column('followers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('follows', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_following_fkey', 'follows', 'users', ['following'], ['id'])
    op.create_foreign_key('follows_followers_fkey', 'follows', 'users', ['followers'], ['id'])
    op.drop_column('follows', 'followed_id')
    op.drop_column('follows', 'follower_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'users', ['post_id'], ['id'])
    # ### end Alembic commands ###
