"""empty message

Revision ID: 72158a7504fc
Revises: 48b0f135892c
Create Date: 2022-02-07 12:43:12.487086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72158a7504fc'
down_revision = '48b0f135892c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('likes_likes_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'])
    op.drop_column('likes', 'likes_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('likes_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_likes_id_fkey', 'likes', 'users', ['likes_id'], ['id'])
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###
