"""empty message

Revision ID: 9c495cf15f1b
Revises: 1750826dc3aa
Create Date: 2022-02-08 15:47:00.045276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c495cf15f1b'
down_revision = '1750826dc3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    op.drop_table('likes_tb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes_tb',
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('posts_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], name='likes_tb_posts_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='likes_tb_users_id_fkey')
    )
    op.drop_table('likes')
    # ### end Alembic commands ###
